/*
 * Dummy
 *
 * Dummy
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Feed - struct for Feed
type Feed struct {
	Article *Article
	Person *Person
}

// ArticleAsFeed is a convenience function that returns Article wrapped in Feed
func ArticleAsFeed(v *Article) Feed {
	return Feed{ Article: v}
}

// PersonAsFeed is a convenience function that returns Person wrapped in Feed
func PersonAsFeed(v *Person) Feed {
	return Feed{ Person: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Feed) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = json.Unmarshal(data, &jsonDict)
	if err != nil {
		return fmt.Errorf("Failed to unmarshal JSON into map for the discrimintor lookup.")
	}

	// check if the discriminator value is 'Article'
	if jsonDict["type"] == "Article" {
		// try to unmarshal JSON data into Article
		err = json.Unmarshal(data, &dst.Article)
		if err == nil {
			return nil // data stored in dst.Article, return on the first match
		} else {
			dst.Article = nil
			return fmt.Errorf("Failed to unmarshal Feed as Article: %s", err.Error())
		}
	}

	// check if the discriminator value is 'Person'
	if jsonDict["type"] == "Person" {
		// try to unmarshal JSON data into Person
		err = json.Unmarshal(data, &dst.Person)
		if err == nil {
			return nil // data stored in dst.Person, return on the first match
		} else {
			dst.Person = nil
			return fmt.Errorf("Failed to unmarshal Feed as Person: %s", err.Error())
		}
	}

	// check if the discriminator value is 'article'
	if jsonDict["type"] == "article" {
		// try to unmarshal JSON data into Article
		err = json.Unmarshal(data, &dst.Article)
		if err == nil {
			return nil // data stored in dst.Article, return on the first match
		} else {
			dst.Article = nil
			return fmt.Errorf("Failed to unmarshal Feed as Article: %s", err.Error())
		}
	}

	// check if the discriminator value is 'person'
	if jsonDict["type"] == "person" {
		// try to unmarshal JSON data into Person
		err = json.Unmarshal(data, &dst.Person)
		if err == nil {
			return nil // data stored in dst.Person, return on the first match
		} else {
			dst.Person = nil
			return fmt.Errorf("Failed to unmarshal Feed as Person: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Feed) MarshalJSON() ([]byte, error) {
	if src.Article != nil {
		return json.Marshal(&src.Article)
	}

	if src.Person != nil {
		return json.Marshal(&src.Person)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Feed) GetActualInstance() (interface{}) {
	if obj.Article != nil {
		return obj.Article
	}

	if obj.Person != nil {
		return obj.Person
	}

	// all schemas are nil
	return nil
}

type NullableFeed struct {
	value *Feed
	isSet bool
}

func (v NullableFeed) Get() *Feed {
	return v.value
}

func (v *NullableFeed) Set(val *Feed) {
	v.value = val
	v.isSet = true
}

func (v NullableFeed) IsSet() bool {
	return v.isSet
}

func (v *NullableFeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeed(val *Feed) *NullableFeed {
	return &NullableFeed{value: val, isSet: true}
}

func (v NullableFeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


