/*
 * Dummy
 *
 * Dummy
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ArticleFeed struct for ArticleFeed
type ArticleFeed struct {
	Type *string `json:"type,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewArticleFeed instantiates a new ArticleFeed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArticleFeed() *ArticleFeed {
	this := ArticleFeed{}
	return &this
}

// NewArticleFeedWithDefaults instantiates a new ArticleFeed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArticleFeedWithDefaults() *ArticleFeed {
	this := ArticleFeed{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ArticleFeed) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleFeed) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ArticleFeed) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ArticleFeed) SetType(v string) {
	o.Type = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ArticleFeed) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArticleFeed) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ArticleFeed) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ArticleFeed) SetTitle(v string) {
	o.Title = &v
}

func (o ArticleFeed) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	return json.Marshal(toSerialize)
}

type NullableArticleFeed struct {
	value *ArticleFeed
	isSet bool
}

func (v NullableArticleFeed) Get() *ArticleFeed {
	return v.value
}

func (v *NullableArticleFeed) Set(val *ArticleFeed) {
	v.value = val
	v.isSet = true
}

func (v NullableArticleFeed) IsSet() bool {
	return v.isSet
}

func (v *NullableArticleFeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArticleFeed(val *ArticleFeed) *NullableArticleFeed {
	return &NullableArticleFeed{value: val, isSet: true}
}

func (v NullableArticleFeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArticleFeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


